name: Build All Platforms

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type (release, debug)'
        required: true
        default: 'release'
        options:
          - 'release'
          - 'debug'
  push:
    tags:
      - v*
    inputs:
      build-type:
        required: true
        type: string
        default: 'release'

jobs:

  linux:
    uses: ./.github/workflows/linux.yml
    with:
      build-type: ${{ github.event.inputs.build-type }}

  windows:
    uses: ./.github/workflows/windows.yml
    with:
      build-type: ${{ github.event.inputs.build-type }}

  macos:
    uses: ./.github/workflows/macos.yml
    with:
      build-type: ${{ github.event.inputs.build-type }}

########################## Create Release ##########################

release:
  runs-on: ubuntu-latest
  needs: [linux, windows, macos]
  if: github.ref_type == 'tag' && contains(github.ref_name, 'v') && github.event.inputs.build-type == 'release'

  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Get version
      id: get_version
      uses: battila7/get-version-action@v2

    - name: Create release notes
      run: |
        cat > CHANGELOG.txt << EOF
        ## Download
        - [Windows](https://github.com/${{ GITHUB_REPOSITORY }}/releases/download/${{ steps.get_version.outputs.version }}/VectorAudio-${{ steps.get_version.outputs.version-without-v }}-Windows.exe)
        - [macOS](https://github.com/${{ GITHUB_REPOSITORY }}/releases/download/${{ steps.get_version.outputs.version }}/VectorAudio-${{ steps.get_version.outputs.version-without-v }}-MacOS.dmg)
        - [Linux](https://github.com/${{ GITHUB_REPOSITORY }}/releases/download/${{ steps.get_version.outputs.version }}/VecorAudio-${{ steps.get_version.outputs.version-without-v }}-Linux.AppImage)

        ---

        ### Added

        ### Changed

        ### Fixed
        EOF

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        name: VectorAudio ${{ steps.get_version.outputs.version }}
        prerelease: true
        draft: true
        body_path: CHANGELOG.txt
        files: VectorAudio*