name: Build VectorAudio

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:

  linux:
    uses: ./.github/workflows/linux.yml

  windows:
    uses: ./.github/workflows/windows.yml

########################## Create Release ##########################

# release:
#   runs-on: ubuntu-latest
#   needs: [linux]
#   if: github.ref_type == 'tag' && contains(github.ref_name, 'v')