name: VectorAudio Release

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type (release, debug)'
        required: true
        default: 'release'
        options:
          - 'release'
          - 'debug'
  push:
    tags:
      - v*

jobs:

  linux:
    uses: ./.github/workflows/linux.yml
    with:
      build-type: ${{ github.event.inputs.build-type }}

  windows:
    uses: ./.github/workflows/windows.yml
    with:
      build-type: ${{ github.event.inputs.build-type }}

  macos:
    uses: ./.github/workflows/macos.yml
    with:
      build-type: ${{ github.event.inputs.build-type }}

########################## Create Release ##########################

# release:
#   runs-on: ubuntu-latest
#   needs: [linux]
#   if: github.ref_type == 'tag' && contains(github.ref_name, 'v')