name: Build

on: push

jobs:
  build:

    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            triplet: x64-linux
    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Restore vcpkg from cache
      uses: actions/cache@v3
      with:
        path: ${{ env.CMAKE_BUILD_DIR }}/vcpkg_installed/
        key: ${{ matrix.triplet }}-${{ hashFiles('vcpkg.json') }}
    
    - if: matrix.os == 'windows-latest'
      name: Setup vcpkg for Windows
      run: ${{ env.VCPKG_ROOT }}/bootstrap-vcpkg.bat

    - if: matrix.os != 'windows-latest'
      name: Setup vcpkg for Unix
      run: ${{ env.VCPKG_ROOT }}/bootstrap-vcpkg.sh
    
    - name: Configure CMake
      run: cmake -S "${{github.workspace}}" -B "${{env.CMAKE_BUILD_DIR}}" -DCMAKE_BUILD_TYPE=Release -DVCPKG_INSTALLED_DIR=${{ env.CMAKE_BUILD_DIR }}/vcpkg_installed/ -DVCPKG_BUILD_TYPE=release -DVCPKG_TARGET_TRIPLET=${{matrix.triplet}}

    - name: Build
      run: cmake --build "${{env.CMAKE_BUILD_DIR}}" --config Release