name: Build

on: push

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        vcpkg_triplet: ['x64-windows']
    env:
      VCPKG_TARGET_TRIPLET: ${{ matrix.vcpkg_triplet }}
      GEN: Ninja
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install latest CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11