name: Build macOS

on:
  workflow_call:
  workflow_dispatch:

env:
  CMAKE_BUILD_DIR: ${{ github.workspace }}/build
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        triplet: ['x64-osx', 'arm64-osx']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Get version
      run: |
        echo "APP_VERSION=$(cat VERSION)" >> $GITHUB_ENV

    - name: Create universal build folder
      run: |
        mkdir build/
        mkdir -p build/extern/afv-native/

    - name: Restore vcpkg from cache
      uses: actions/cache@v3
      with:
        path: ${{ matrix.triplet }}_build/vcpkg_installed/
        key: ${{ matrix.triplet }}-${{ hashFiles('vcpkg.json') }}

    - name: Setup vcpkg
      run: ${{ env.VCPKG_ROOT }}/bootstrap-vcpkg.sh

    - name: Configure CMake
      run: cmake -S "${{ github.workspace }}" -B "${{ matrix.triplet }}_build" -DCMAKE_BUILD_TYPE=Release -DVCPKG_INSTALLED_DIR=${{ matrix.triplet }}_build/vcpkg_installed/ -DVCPKG_BUILD_TYPE=release -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} -DCMAKE_OSX_ARCHITECTURES=$([[ "${{ matrix.triplet }}" == 'arm64-osx' ]] && echo 'arm64' || echo 'x86_64')

    - name: Build
      run: cmake --build "${{ matrix.triplet }}_build" --config Release
  
  package:
    needs: [build]
    runs-on: macos-latest

    steps:
    - name: Create universal binary
      run: |
        lipo -create arm64-osx_build/libafv_native.dylib x64-osx_build/libafv_native.dylib -output build/extern/afv-native/libafv_native.dylib
        lipo -create arm64-osx_build/vector_audio x64-osx_build/vector_audio -output build/vector_audio

    - name: Bundle application
      run: ./bundle_osx.sh

    - name: Create DMG
      run: |
        brew install create-dmg
        create-dmg --volname "VectorAudio Installer" --app-drop-link 600 185 --window-size 800 400 --icon "VectorAudio.app" 200 190 "VectorAudio-${{ env.APP_VERSION }}-Universal.dmg" "build/VectorAudio.app"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: macOS-${{ env.APP_VERSION }}.zip
        path: |
          VectorAudio-${{ env.APP_VERSION }}-Universal.dmg
